# @package _global_
wrappers:
  - type: LastActionWrapper
  - type: FrameStackObservation
    params:
      stack_size: 10
  - type: NormalizeObservation
    params:
      epsilon: 1.0e-8
temporal_mode: frame_stack
